language: objective-c
osx_image: xcode6.4
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -project 'CCHBinaryData Example/CCHBinaryData Example.xcodeproj' -scheme 'CCHBinaryData Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -configuration Debug test | xcpretty -c
