language: objective-c
before_install:
  - gem install xcpretty -N
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -project 'CCHBinaryData Example/CCHBinaryData Example.xcodeproj' -scheme 'CCHBinaryData Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -configuration Debug test | xcpretty -c
